# --- Stage 1 : Build ---
FROM golang:1.24-alpine AS builder

# Install git for go modules
RUN apk add --no-cache git

WORKDIR /app

# Copy source code
COPY ./ ./

# Download dependencies
RUN go mod download

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /servo main.go

# --- Stage 2: Run ---
FROM alpine:latest

WORKDIR /root/

# Copy binary from builder
COPY --from=builder /servo .

# Expose the default port
EXPOSE 8080

# Command to run
CMD ["./servo"]
